### ISSUE TITLE
Integration of Safety and Security Indicator in the Social Fabric Model 

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Guadalajara#11]
Discussing with the team we agreed that @LeticiaIG and @gamalielpalomo will integrate some of the safety and security indicators in the ABM Model

A first version of the documentation can be found here 

https://github.com/CityScope/CSL_Guadalajara/wiki

**Comment by LeticiaIG** [comment]
First iteration has been made in this commit where we have integrated: C1,C2 and C7

https://github.com/CityScope/CSL_Guadalajara/commit/b2ba3583c76ea24f6e85a7c3e08325a5a4aae2f5

**Comment by agrignard** [comment]
Great!! Happy to see that the synergy between @LeticiaIG and @gamalielpalomo is working!!!

**Comment by gamalielpalomo** [comment]
Okay! Currently working on agents profiles, also in indicators valuation according to hour_of_the_day, and profile.

**Comment by agrignard** [comment]
@gamalielpalomo any update on this one, this is also related to #21
