### ISSUE TITLE
Model stops every(n) steps to recompute indicators

### ISSUE THREAD

**Issue by gamalielpalomo** [CityScope/CSL_Guadalajara#17]
Every n steps, each agent recomputes its perception value. This makes the simulation to freeze at that point when we use a considerable number of agents. How can I update indicators values for each agent and not to have these pauses? I tried with paralelization, but it didnt make difference.

`reflex update_indicators_values when:every(10#minute)`

**Comment by agrignard** [comment]
Is something you need to do for everyone every 10 minutes? One solution could be to do this update not for everyone evry 10 minutes but for just a certain amont
like doing this
````
reflex update_indicators_values when:every(10#minute) and flip(0.1)
````

**Comment by gamalielpalomo** [comment]
Ok, done!

**Comment by gamalielpalomo** [comment]
This reflex is executed by each agent to update its perception according to the indicators. This is needed as they move and that value may change depending on the location.

**Comment by agrignard** [comment]
Great!
