### ISSUE TITLE
TO DO LIST MAY 2020

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Guadalajara#22]
Aspect
- Create one aspect to trigger  each parameter by pressing 1,2,3,4,5 and parameter on the left
- Create one aspect with every parameter using cylinder

Social Graph
- Use one color per family
- For each agent add a user_command to be able to click on the agent and show its family, friends, 

Building
- Add the key building (church, school) in the .shp file by adding an attribute type and defining the color in GAMA

- Perception
I would keep the color for a global view of the map
And maybe let's explore something else for individual

- Play with sunlight by changing the background of the display (just keep it as a boolean parameter)

**Comment by gamalielpalomo** [comment]
Aspect

- We have added a parameter to change visualization of perception according to different Indicators.
- I did not find how to incorporate event listener to catch key pressed.

Social Graph

- We added two user_command to visualize agent's family and friends.

**Comment by gamalielpalomo** [comment]
We have also the option of showing perception as part of the physical layer. 

![image](https://user-images.githubusercontent.com/19692636/83150690-2e0da580-a0c1-11ea-8fe1-a763e86db89e.png)

**Comment by LAAP** [comment]
Hi @gamalielpalomo 

This is looking great! Please, can you explain a bit how perception is being visualized in the map? I think that there is a lot of potential here

**Comment by gamalielpalomo** [comment]
Hi @LAAP 
Perception is calculated according to the valuation of the environmental indicators. Each agent is able to watch around and determine how safe it feels calculating the safety_perception value using a weighted sum (where weights are the importance each agent gives to each indicator). We have different groups of indicators that include: formal surveillence, artificial lighting, street maintenance, natural surveillance. 

Then, in the simulation we can show safety perception of the streets, or we can show individual perception of every agent (as in the following image).

![image](https://user-images.githubusercontent.com/19692636/83528035-3d6c6480-a4ae-11ea-9e7f-dc138db5972d.png)

During the simulation in GAMA we can choose whether show each agent's perception, overall perception, perception by group of indicators. 
We also can show familiar and frienship ties.
![image](https://user-images.githubusercontent.com/19692636/83528843-372ab800-a4af-11ea-9203-c4731fa59c1e.png)

**Comment by LAAP** [comment]
@gamalielpalomo ,
This is great! Good Job, I see that the integration between @LeticiaIG 's indicators and the Simulation is already happening and robust. Congrats

**Comment by agrignard** [comment]
Great job @gamalielpalomo as we discussed with @LeticiaIG and you it will be great if you can start to produce a video that explain what is already implemented (knowing that there are already a lot of things we can show)
