### ISSUE TITLE
Aggregated HeatMap

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Guadalajara#3]
It can be nice to have an aggregated heatmap to see where the crime occurs more. Maybe a third display we each time there is a crime you increment a value for a cell

**Comment by gamalielpalomo** [comment]
I have added a second heat map to the model to show the number of crimes committed. This was aggregated to the secondary map and the heat map of risky zones was moved to the main display. I have a trouble showing the agents over this heat map, the agents (people and offenders) seem to hide behind the map.
